/// Generated by terra, DO NOT MODIFY BY HAND.

#ifndef FAKE_ILOCALSPATIALAUDIOENGINE_INTERNAL_H_
#define FAKE_ILOCALSPATIALAUDIOENGINE_INTERNAL_H_

#include "IAgoraSpatialAudio.h"

namespace agora {
namespace rtc {
class FakeILocalSpatialAudioEngineInternal
    : public agora::rtc::ILocalSpatialAudioEngine {
#ifndef AGORA_SPATIAL_AUDIO_H virtual void release() override {}
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int setMaxAudioRecvCount(int maxCount) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int setAudioRecvRange(float range) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int setDistanceUnit(float unit) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int updateSelfPosition(float[3] position, float[3] axisForward,
                                 float[3] axisRight, float[3] axisUp) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int
  updateSelfPositionEx(float[3] position, float[3] axisForward,
                       float[3] axisRight, float[3] axisUp,
                       agora::rtc::RtcConnection const &connection) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int updatePlayerPositionInfo(
      int playerId,
      agora::rtc::RemoteVoicePositionInfo const &positionInfo) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int setParameters(char const *params) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int muteLocalAudioStream(bool mute) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int muteAllRemoteAudioStreams(bool mute) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int
  initialize(agora::rtc::LocalSpatialAudioConfig const &config) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int updateRemotePosition(
      agora::rtc::uid_t uid,
      agora::rtc::RemoteVoicePositionInfo const &posInfo) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int
  updateRemotePositionEx(agora::rtc::uid_t uid,
                         agora::rtc::RemoteVoicePositionInfo const &posInfo,
                         agora::rtc::RtcConnection const &connection) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int removeRemotePosition(agora::rtc::uid_t uid) override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int
  removeRemotePositionEx(agora::rtc::uid_t uid,
                         agora::rtc::RtcConnection const &connection) override {
    return 0;
  }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int clearRemotePositions() override { return 0; }
#endif

#ifndef AGORA_SPATIAL_AUDIO_H
  virtual int
  clearRemotePositionsEx(agora::rtc::RtcConnection const &connection) override {
    return 0;
  }
#endif
};
}
}

#endif // FAKE_ILOCALSPATIALAUDIOENGINE_INTERNAL_H_
