include: shared:rtc_4.0.1.203/shared_configs.yaml

language: dart

legacy_renders:
  # - DartSyntaxRender
  - DartEventHandlerParamJsonRender
  # - DartCallApiRender
  # - DartEventHandlerRender
  - DartStructToJsonSerializableRender
  - DartCallApiEventHandlerBufferExtRender
  - DartForwardExportRender
